"""
Universal Knowledge Core — Schemas Package.
"""

from app.intelligence.schemas.content_type import ContentType
from app.intelligence.schemas.provenance import KnowledgeProvenance
from app.intelligence.schemas.payloads import (
    EvidenceType,
    ConceptPayload,
    ProcedureStep,
    ProcedurePayload,
    VariableDefinition,
    FormalPayload,
    QuantitativeEvidenceData,
    QualitativeEvidenceData,
    EvidenceSourceMetadata,
    EvidencePayload,
    ArgumentPayload,
    PedagogicalPayload,
    KnowledgePayloadUnion,
)
from app.intelligence.schemas.knowledge_unit import (
    KnowledgeCategory,
    IntrinsicImportance,
    ResolutionStatus,
    KnowledgeUnit,
    generate_stable_knowledge_id,
    normalize_content_for_identity,
)
from app.intelligence.schemas.relationships import (
    RelationshipType,
    RelationshipOrigin,
    RelationshipEvidence,
    KnowledgeRelationship,
)
from app.intelligence.schemas.intent_constraints import (
    EducationLevel,
    ExpertiseLevel,
    AudienceProfile,
    LengthConstraint,
    DepthConstraint,
    CitationConstraint,
    FormatIntentConstraint,
    IntentConstraints,
    GenerationRequest,
    ResolvedArtifactIntent,
)
from app.intelligence.schemas.universal_manifest import UniversalKnowledgeManifest

# Legacy Schemas Compatibility
from app.intelligence.schemas.legacy_schemas import (
    AIClassificationOutput,
    AIQualityCritiqueOutput,
    AIRelationshipOutput,
    AIVisualIntentOutput,
    AnalysisResult,
    BlueprintCandidateType,
    BlueprintProposal,
    ConclusionTrace,
    ConfidenceLevel,
    ContentDensity,
    ContentGroup,
    ContentRelationship,
    ContentUnit,
    DocumentGenre,
    DocumentMode,
    FailureCategory,
    HumanOverride,
    ImportanceScore,
    JobState,
    KtiBab,
    PipelineJob,
    RecommendationBasis,
    ResearchTraceability,
    TraceabilityWarning,
    VisualIntent,
    VisualIntentResult,
    VisualizationCandidate,
    VisualizationPurpose,
)

__all__ = [
    "ContentType",
    "KnowledgeProvenance",
    "EvidenceType",
    "ConceptPayload",
    "ProcedureStep",
    "ProcedurePayload",
    "VariableDefinition",
    "FormalPayload",
    "QuantitativeEvidenceData",
    "QualitativeEvidenceData",
    "EvidenceSourceMetadata",
    "EvidencePayload",
    "ArgumentPayload",
    "PedagogicalPayload",
    "KnowledgePayloadUnion",
    "KnowledgeCategory",
    "IntrinsicImportance",
    "ResolutionStatus",
    "KnowledgeUnit",
    "generate_stable_knowledge_id",
    "normalize_content_for_identity",
    "RelationshipType",
    "RelationshipOrigin",
    "RelationshipEvidence",
    "KnowledgeRelationship",
    "EducationLevel",
    "ExpertiseLevel",
    "AudienceProfile",
    "LengthConstraint",
    "DepthConstraint",
    "CitationConstraint",
    "FormatIntentConstraint",
    "IntentConstraints",
    "GenerationRequest",
    "ResolvedArtifactIntent",
    "UniversalKnowledgeManifest",
    # Legacy exports
    "AIClassificationOutput",
    "AIQualityCritiqueOutput",
    "AIRelationshipOutput",
    "AIVisualIntentOutput",
    "AnalysisResult",
    "BlueprintCandidateType",
    "BlueprintProposal",
    "ConclusionTrace",
    "ConfidenceLevel",
    "ContentDensity",
    "ContentGroup",
    "ContentRelationship",
    "ContentUnit",
    "DocumentGenre",
    "DocumentMode",
    "FailureCategory",
    "HumanOverride",
    "ImportanceScore",
    "JobState",
    "KtiBab",
    "PipelineJob",
    "RecommendationBasis",
    "ResearchTraceability",
    "TraceabilityWarning",
    "VisualIntent",
    "VisualIntentResult",
    "VisualizationCandidate",
    "VisualizationPurpose",
]
