"""
Universal Knowledge Core — ContentType Enum.
"""

from enum import Enum


class ContentType(str, Enum):
    """Semantic type of a ContentUnit.

    Divided into two groups:
    - General information types: applicable to any document genre.
    - KTI / Research semantic roles: specific to research reports (BAB 1–5).
    """

    # ── General information types ──────────────────────────────────────────
    FACT = "fact"
    DEFINITION = "definition"
    EXPLANATION = "explanation"
    CONTEXT = "context"
    BACKGROUND = "background"
    PROBLEM = "problem"
    QUESTION = "question"
    OBJECTIVE = "objective"
    BENEFIT = "benefit"
    HYPOTHESIS = "hypothesis"
    CONCEPT = "concept"
    THEORY = "theory"
    PRIOR_RESEARCH = "prior_research"
    RESEARCH_GAP = "research_gap"
    METHOD = "method"
    PROCEDURE = "procedure"
    INSTRUCTION = "instruction"
    PROCESS = "process"
    SEQUENCE = "sequence"
    COMPARISON = "comparison"
    CAUSE_EFFECT = "cause_effect"
    EXAMPLE = "example"
    EVIDENCE = "evidence"
    DATA = "data"
    RESULT = "result"
    FINDING = "finding"
    ARGUMENT = "argument"
    CLAIM = "claim"
    ANALYSIS = "analysis"
    INTERPRETATION = "interpretation"
    DISCUSSION = "discussion"
    LIMITATION = "limitation"
    IMPLICATION = "implication"
    SUMMARY = "summary"
    CONCLUSION = "conclusion"
    RECOMMENDATION = "recommendation"
    FUTURE_WORK = "future_work"
    WARNING = "warning"
    TIP = "tip"
    REFLECTION = "reflection"
    FORMULA = "formula"
    REFERENCE = "reference"
    CHECKLIST = "checklist"
    HIERARCHY = "hierarchy"
    TITLE = "title"
    INTRODUCTION = "introduction"
    ACTIVITY = "activity"
    OTHER = "other"

    # ── KTI / Research semantic roles ──────────────────────────────────────
    RESEARCH_PROBLEM = "research_problem"
    RESEARCH_CONTEXT = "research_context"
    RESEARCH_QUESTION = "research_question"
    RESEARCH_OBJECTIVE = "research_objective"
    RESEARCH_BENEFIT = "research_benefit"
    RESEARCH_HYPOTHESIS = "research_hypothesis"
    THEORETICAL_FOUNDATION = "theoretical_foundation"
    KEY_CONCEPT = "key_concept"
    VARIABLE_OR_FACTOR = "variable_or_factor"
    RESEARCH_PRIOR = "research_prior"
    RESEARCH_GAP_KTI = "research_gap_kti"
    RESEARCH_METHOD = "research_method"
    RESEARCH_DESIGN = "research_design"
    RESEARCH_SUBJECT = "research_subject"
    RESEARCH_OBJECT = "research_object"
    TIME_AND_PLACE = "time_and_place"
    INSTRUMENT = "instrument"
    TOOL = "tool"
    MATERIAL = "material"
    DATA_SOURCE = "data_source"
    DATA_COLLECTION = "data_collection"
    RESEARCH_PROCEDURE = "research_procedure"
    DATA_ANALYSIS_METHOD = "data_analysis_method"
    DATA_POINT = "data_point"
    RESEARCH_RESULT = "research_result"
    RESEARCH_FINDING = "research_finding"
    RESEARCH_INTERPRETATION = "research_interpretation"
    RESEARCH_DISCUSSION = "research_discussion"
    THEORY_CONNECTION = "theory_connection"
    PRIOR_RESEARCH_COMPARISON = "prior_research_comparison"
    RESEARCH_LIMITATION = "research_limitation"
    PRACTICAL_IMPLICATION = "practical_implication"
    THEORETICAL_IMPLICATION = "theoretical_implication"
    RESEARCH_SUMMARY = "research_summary"
    RESEARCH_CONCLUSION = "research_conclusion"
    RESEARCH_RECOMMENDATION = "research_recommendation"
    FUTURE_RESEARCH = "future_research"
    RESEARCH_FUTURE_WORK = "research_future_work"
    RESEARCH_IMPLICATION = "research_implication"
    HYPOTHESIS_EVALUATION = "hypothesis_evaluation"
    VISUALIZATION_CANDIDATE = "visualization_candidate"
